# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'
use_frameworks!
def eventgo_pods

pod 'Firebase/Core'
pod 'Google/Analytics'
pod 'Firebase/Core'
pod 'Firebase/AdMob'
pod 'Firebase/Crash'
pod 'RealmSwift', '~> 2.4'
pod 'HTMLReader', '~> 2.0'
pod 'OAStackView', '~> 1.0'
pod 'UICollectionViewLeftAlignedLayout'
pod 'Google/SignIn'
pod 'XCGLogger', '~> 4.0.0'
pod 'SCLAlertView', '~> 0.7'
pod 'ChameleonFramework', '~> 2.1'
pod 'SwiftyJSON'

pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'GoogleMaps'
pod 'AnimatedTextInput', '~> 0.4'
pod 'AlamofireImage', '~> 3.1'
pod 'ESPullToRefresh', '~> 2.6'
pod 'RxSwift',    '~> 3.0'
pod 'RxCocoa',    '~> 3.0'
pod 'MBProgressHUD', '~> 1.0'
pod 'Toaster', '~> 2.0'
pod 'Pulsator'
pod 'JDAnimationKit'
pod 'SnapKit'
pod 'DZNEmptyDataSet'
pod 'EZLoadingActivity'
end

target 'EventGo-iOSApp' do
  use_frameworks!

    eventgo_pods

  target 'EventGo-iOSAppTests' do
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
